"""otp destination can be an email

Revision ID: 4159f5a1d1d5
Revises: 65f4821e82d8
Create Date: 2026-10-01 09:12:14.872158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4159f5a1d1d5'
down_revision = '65f4821e82d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=254),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_challenges', schema=None) as batch_op:
        batch_op.alter_column('contact',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
