"""complainant email

Revision ID: 65f4821e82d8
Revises: d2411b5ded87
Create Date: 2026-10-01 09:09:12.220371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f4821e82d8'
down_revision = 'd2411b5ded87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complainants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=254), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complainants', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
