"""urgency, consent, map pin, info requests, docket movements, reviews, notifications, account status

Revision ID: 75bb21a0713c
Revises: 4159f5a1d1d5
Create Date: 2026-10-02 00:42:06.383118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bb21a0713c'
down_revision = '4159f5a1d1d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('docket_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledgement_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('docket_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docket_movements_docket_id'), ['docket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_docket_movements_to_user_id'), ['to_user_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('commander_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=40), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('further_action', sa.Text(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['commander_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_docket_id'), ['docket_id'], unique=False)

    with op.batch_alter_table('intakes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgent', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('info_request', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('info_requested_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('info_requested_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('info_response', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('info_responded_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_intakes_info_requested_by', 'users', ['info_requested_by'], ['id'])

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('outcome', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('next_action', sa.Text(), nullable=True))

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personnel_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('account_status', sa.String(length=20), server_default='active', nullable=False))
        batch_op.add_column(sa.Column('status_reason', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_users_personnel_number', ['personnel_number'])

    # ### end Alembic commands ###
    op.execute("UPDATE users SET account_status = 'deactivated' WHERE is_active = false")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('uq_users_personnel_number', type_='unique')
        batch_op.drop_column('status_reason')
        batch_op.drop_column('account_status')
        batch_op.drop_column('phone')
        batch_op.drop_column('personnel_number')

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('next_action')
        batch_op.drop_column('outcome')
        batch_op.drop_column('entry_type')

    with op.batch_alter_table('intakes', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_intakes_info_requested_by', type_='foreignkey')
        batch_op.drop_column('info_responded_at')
        batch_op.drop_column('info_response')
        batch_op.drop_column('info_requested_by')
        batch_op.drop_column('info_requested_at')
        batch_op.drop_column('info_request')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('consent_at')
        batch_op.drop_column('urgent')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_docket_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('docket_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docket_movements_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_docket_movements_docket_id'))

    op.drop_table('docket_movements')
    with op.batch_alter_table('staff_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_notifications_user_id'))

    op.drop_table('staff_notifications')
    # ### end Alembic commands ###
