"""initial schema

Revision ID: 92caa1baa6db
Revises: 
Create Date: 2026-09-29 02:34:26.196032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92caa1baa6db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complainants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complainant_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.Column('id_number', sa.String(length=13), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complainant_number')
    )
    with op.batch_alter_table('complainants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complainants_id_number'), ['id_number'], unique=False)

    op.create_table('counters',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('otp_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('contact', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=60), nullable=True),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specialisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('province', sa.String(length=60), nullable=False),
    sa.Column('service_areas', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('required_specialisation_id', sa.Integer(), nullable=True),
    sa.Column('sla_days', sa.Integer(), nullable=False),
    sa.Column('default_priority', sa.String(length=10), nullable=False),
    sa.Column('protected_from_withdrawal', sa.Boolean(), nullable=False),
    sa.Column('requires_classification', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['required_specialisation_id'], ['specialisations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('official', 'detective', 'commander', 'admin', name='user_role'), nullable=False),
    sa.Column('rank', sa.String(length=60), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('specialisation_id', sa.Integer(), nullable=True),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('max_caseload', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['specialisation_id'], ['specialisations.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('access_reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_hash')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_case_id'), ['case_id'], unique=False)

    op.create_table('intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_number', sa.String(length=30), nullable=False),
    sa.Column('track_token', sa.String(length=64), nullable=False),
    sa.Column('complainant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('incident_description', sa.Text(), nullable=False),
    sa.Column('incident_location', sa.String(length=255), nullable=False),
    sa.Column('incident_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('suspect', sa.JSON(), nullable=False),
    sa.Column('witnesses_reported', sa.JSON(), nullable=False),
    sa.Column('disposition', sa.String(length=20), nullable=False),
    sa.Column('disposed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disposed_by', sa.Integer(), nullable=True),
    sa.Column('docket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['complainant_id'], ['complainants.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disposed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intake_number')
    )
    with op.batch_alter_table('intakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intakes_complainant_id'), ['complainant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intakes_station_id'), ['station_id'], unique=False)

    op.create_table('dockets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cas_number', sa.String(length=30), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('complainant_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('registered_by', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.String(length=30), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detective_id', sa.Integer(), nullable=True),
    sa.Column('closure_type', sa.String(length=120), nullable=True),
    sa.Column('brought_forward_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['complainant_id'], ['complainants.id'], ),
    sa.ForeignKeyConstraint(['detective_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ),
    sa.ForeignKeyConstraint(['registered_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cas_number')
    )
    with op.batch_alter_table('dockets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dockets_detective_id'), ['detective_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dockets_intake_id'), ['intake_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dockets_station_id'), ['station_id'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_intake_id'), ['intake_id'], unique=False)

    op.create_table('refusals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('reason_category', sa.String(length=120), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=False),
    sa.Column('duplicate_of', sa.String(length=40), nullable=True),
    sa.Column('missing_element', sa.String(length=20), nullable=True),
    sa.Column('definition_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('complainant_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cosigned_by', sa.Integer(), nullable=True),
    sa.Column('cosigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cosign_note', sa.Text(), nullable=False),
    sa.Column('definition_checked', sa.Boolean(), nullable=False),
    sa.Column('reversed_official_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cosigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reversed_official_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refusals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refusals_intake_id'), ['intake_id'], unique=False)

    op.create_table('arrests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('accused_name', sa.String(length=120), nullable=False),
    sa.Column('arrested_by', sa.Integer(), nullable=True),
    sa.Column('arrest_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('charge_description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['arrested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('arrests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_arrests_docket_id'), ['docket_id'], unique=False)

    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('detective_id', sa.Integer(), nullable=False),
    sa.Column('previous_detective_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assignment_method', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason_category', sa.String(length=60), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['detective_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['previous_detective_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignments_docket_id'), ['docket_id'], unique=False)

    op.create_table('closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('category_label', sa.String(length=120), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('warrant_reference', sa.String(length=60), nullable=True),
    sa.Column('circulation_reference', sa.String(length=60), nullable=True),
    sa.Column('discrepancy_report', sa.Text(), nullable=True),
    sa.Column('prosecutor_reference', sa.String(length=60), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checklist_confirmed', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_closures_docket_id'), ['docket_id'], unique=False)

    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=True),
    sa.Column('intake_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('raised_by_complainant', sa.Boolean(), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('commander_id', sa.Integer(), nullable=True),
    sa.Column('decision_maker_id', sa.Integer(), nullable=True),
    sa.Column('routed_upward', sa.Boolean(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['commander_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decision_maker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escalations_docket_id'), ['docket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_escalations_intake_id'), ['intake_id'], unique=False)

    op.create_table('handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('handed_by', sa.Integer(), nullable=True),
    sa.Column('recipient_name', sa.String(length=120), nullable=False),
    sa.Column('recipient_organisation', sa.String(length=120), nullable=False),
    sa.Column('handover_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('receipt_reference', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['handed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handovers_docket_id'), ['docket_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('responded_by', sa.Integer(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_docket_id'), ['docket_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_intake_id'), ['intake_id'], unique=False)

    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_history_docket_id'), ['docket_id'], unique=False)

    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=False),
    sa.Column('to_station_id', sa.Integer(), nullable=False),
    sa.Column('transferred_by', sa.Integer(), nullable=True),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['from_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['to_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['transferred_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_docket_id'), ['docket_id'], unique=False)

    op.create_table('withdrawals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=True),
    sa.Column('reason_category', sa.String(length=120), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('protected_category', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawals_intake_id'), ['intake_id'], unique=False)

    op.create_table('witnesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=60), nullable=False),
    sa.Column('identified_by', sa.Integer(), nullable=True),
    sa.Column('identified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('statement_text', sa.Text(), nullable=False),
    sa.Column('statement_taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_statement_reason', sa.Text(), nullable=False),
    sa.Column('reported_by_complainant', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['identified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('witnesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_witnesses_docket_id'), ['docket_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('exhibit_number', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.String(length=60), nullable=True),
    sa.Column('collected_by', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_holder_id', sa.Integer(), nullable=True),
    sa.Column('storage_location', sa.String(length=255), nullable=False),
    sa.Column('saps13_number', sa.String(length=60), nullable=True),
    sa.Column('image_data_url', sa.String(length=255), nullable=True),
    sa.Column('suspect_name', sa.String(length=120), nullable=True),
    sa.Column('suspect_id_number', sa.String(length=13), nullable=True),
    sa.Column('suspect_photo_data_url', sa.String(length=255), nullable=True),
    sa.Column('linked_arrest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collected_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_holder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['linked_arrest_id'], ['arrests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_docket_id'), ['docket_id'], unique=False)

    op.create_table('complainant_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('data_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('linked_exhibit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], ),
    sa.ForeignKeyConstraint(['linked_exhibit_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complainant_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complainant_evidence_intake_id'), ['intake_id'], unique=False)

    op.create_table('custody',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custody', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custody_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('forensics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docket_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lab_reference', sa.String(length=60), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('result_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accounted_for_reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['docket_id'], ['dockets.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forensics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forensics_docket_id'), ['docket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forensics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forensics_docket_id'))

    op.drop_table('forensics')
    with op.batch_alter_table('custody', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custody_evidence_id'))

    op.drop_table('custody')
    with op.batch_alter_table('complainant_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complainant_evidence_intake_id'))

    op.drop_table('complainant_evidence')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_docket_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('witnesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_witnesses_docket_id'))

    op.drop_table('witnesses')
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawals_intake_id'))

    op.drop_table('withdrawals')
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_docket_id'))

    op.drop_table('transfers')
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_docket_id'))

    op.drop_table('status_history')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_intake_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_docket_id'))

    op.drop_table('notes')
    with op.batch_alter_table('handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handovers_docket_id'))

    op.drop_table('handovers')
    with op.batch_alter_table('escalations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escalations_intake_id'))
        batch_op.drop_index(batch_op.f('ix_escalations_docket_id'))

    op.drop_table('escalations')
    with op.batch_alter_table('closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_closures_docket_id'))

    op.drop_table('closures')
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignments_docket_id'))

    op.drop_table('assignments')
    with op.batch_alter_table('arrests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_arrests_docket_id'))

    op.drop_table('arrests')
    with op.batch_alter_table('refusals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refusals_intake_id'))

    op.drop_table('refusals')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_intake_id'))

    op.drop_table('files')
    with op.batch_alter_table('dockets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dockets_station_id'))
        batch_op.drop_index(batch_op.f('ix_dockets_intake_id'))
        batch_op.drop_index(batch_op.f('ix_dockets_detective_id'))

    op.drop_table('dockets')
    with op.batch_alter_table('intakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intakes_station_id'))
        batch_op.drop_index(batch_op.f('ix_intakes_complainant_id'))

    op.drop_table('intakes')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_case_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('categories')
    op.drop_table('stations')
    op.drop_table('specialisations')
    op.drop_table('otp_challenges')
    op.drop_table('counters')
    with op.batch_alter_table('complainants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complainants_id_number'))

    op.drop_table('complainants')
    # ### end Alembic commands ###
    sa.Enum(name='user_role').drop(op.get_bind(), checkfirst=True)
